//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPVendor {

        public CPVendor()
        {
            this.VendorSid = @"CONVERT([nvarchar](36),newid())";
            OnCreated();
        }

        public virtual long VendorId
        {
            get;
            set;
        }

        public virtual string VendorSid
        {
            get;
            set;
        }

        public virtual string VendorNameEn
        {
            get;
            set;
        }

        public virtual string VendorNameAr
        {
            get;
            set;
        }

        public virtual string VendorEmail
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
