//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPOutEmail {

        public CPOutEmail()
        {
            OnCreated();
        }

        public virtual long OutEmailId
        {
            get;
            set;
        }

        public virtual string To
        {
            get;
            set;
        }

        public virtual string Subject
        {
            get;
            set;
        }

        public virtual string Body
        {
            get;
            set;
        }

        public virtual bool IsHtml
        {
            get;
            set;
        }

        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }

        public virtual bool IsSent
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> SentDate
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
