//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPTenant {

        public CPTenant()
        {
            this.CPTenantDomains = new List<CPTenantDomain>();
            this.CPUsers = new List<CPUser>();
            OnCreated();
        }

        public virtual long TenantId
        {
            get;
            set;
        }

        public virtual string TenantSId
        {
            get;
            set;
        }

        public virtual string Host
        {
            get;
            set;
        }

        public virtual string LogoUri
        {
            get;
            set;
        }

        public virtual string FooterLogoUri
        {
            get;
            set;
        }

        public virtual bool IsDomainAccessControl
        {
            get;
            set;
        }

        public virtual bool EnableAccountActivation
        {
            get;
            set;
        }

        public virtual string SessionIdName
        {
            get;
            set;
        }

        public virtual int SessionTimeout
        {
            get;
            set;
        }

        public virtual IList<CPTenantDomain> CPTenantDomains
        {
            get;
            set;
        }

        public virtual IList<CPUser> CPUsers
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
