//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPWorkflowInstance {

        public CPWorkflowInstance()
        {
            this.CPWorkflowAssignees = new List<CPWorkflowAssignee>();
            this.CPWorkflowInstanceStatus = new List<CPWorkflowInstanceStatus>();
            OnCreated();
        }

        public virtual long InstanceId
        {
            get;
            set;
        }

        public virtual string InstanceSId
        {
            get;
            set;
        }

        public virtual long MetadataId
        {
            get;
            set;
        }

        public virtual int InstanceStatus
        {
            get;
            set;
        }

        public virtual string CycleId
        {
            get;
            set;
        }

        public virtual string StepId
        {
            get;
            set;
        }

        public virtual string StepNameCaption
        {
            get;
            set;
        }

        public virtual string StepCaption
        {
            get;
            set;
        }

        public virtual long RequesterId
        {
            get;
            set;
        }

        public virtual string BaseClass
        {
            get;
            set;
        }

        public virtual string Data
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> SLATimer
        {
            get;
            set;
        }

        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }

        public virtual string InstanceBrief
        {
            get;
            set;
        }

        public virtual IList<CPWorkflowAssignee> CPWorkflowAssignees
        {
            get;
            set;
        }

        public virtual CPUser CPUser
        {
            get;
            set;
        }

        public virtual IList<CPWorkflowInstanceStatus> CPWorkflowInstanceStatus
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
