//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPUsersBeforeSync {

        public CPUsersBeforeSync()
        {
            OnCreated();
        }

        public virtual long UserId
        {
            get;
            set;
        }

        public virtual string UserSId
        {
            get;
            set;
        }

        public virtual long TenantId
        {
            get;
            set;
        }

        public virtual string UserName
        {
            get;
            set;
        }

        public virtual string Password
        {
            get;
            set;
        }

        public virtual string EmailAddress
        {
            get;
            set;
        }

        public virtual System.Nullable<int> EmployeeId
        {
            get;
            set;
        }

        public virtual string Title
        {
            get;
            set;
        }

        public virtual string FirstName
        {
            get;
            set;
        }

        public virtual string SecondName
        {
            get;
            set;
        }

        public virtual string ThirdName
        {
            get;
            set;
        }

        public virtual string LastName
        {
            get;
            set;
        }

        public virtual string FullNameEn
        {
            get;
            set;
        }

        public virtual string FullNameAr
        {
            get;
            set;
        }

        public virtual bool IsManager
        {
            get;
            set;
        }

        public virtual long ManagerId
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgUnitId
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgLv1Id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgLv2Id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgLv3Id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgLv4Id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgLv5Id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgLv6Id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> OrgLv7Id
        {
            get;
            set;
        }

        public virtual System.Nullable<int> DesignationId
        {
            get;
            set;
        }

        public virtual string DesignationEn
        {
            get;
            set;
        }

        public virtual string DesignationAr
        {
            get;
            set;
        }

        public virtual int Grade
        {
            get;
            set;
        }

        public virtual string Gender
        {
            get;
            set;
        }

        public virtual System.DateTime DateOfBirth
        {
            get;
            set;
        }

        public virtual int NationalityId
        {
            get;
            set;
        }

        public virtual System.DateTime JoinedDate
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> TerminationDate
        {
            get;
            set;
        }

        public virtual bool IsContractor
        {
            get;
            set;
        }

        public virtual bool IsArabic
        {
            get;
            set;
        }

        public virtual bool IsActive
        {
            get;
            set;
        }

        public virtual bool IsLocked
        {
            get;
            set;
        }

        public virtual int AccountType
        {
            get;
            set;
        }

        public virtual System.DateTime LastLoginDate
        {
            get;
            set;
        }

        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
