//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class dbCoreWorkflowMetadata {

        public dbCoreWorkflowMetadata()
        {
            OnCreated();
        }

        public virtual long MetadataId
        {
            get;
            set;
        }

        public virtual string MetadataSId
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> IsListed
        {
            get;
            set;
        }

        public virtual System.Nullable<long> WorkflowCategoryId
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual string BaseClass
        {
            get;
            set;
        }

        public virtual string FileLocation
        {
            get;
            set;
        }

        public virtual string BaseProjectName
        {
            get;
            set;
        }

        public virtual CPWorkflowCategory CPWorkflowCategory
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
