//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPUserTempAssignment {

        public CPUserTempAssignment()
        {
            OnCreated();
        }

        public virtual long UserId
        {
            get;
            set;
        }

        public virtual long UnitId
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> IsManager
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> StartDate
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CPUserTempAssignment toCompare = obj as CPUserTempAssignment;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.UserId, toCompare.UserId))
            return false;
          if (!Object.Equals(this.UnitId, toCompare.UnitId))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + UserId.GetHashCode();
          hashCode = (hashCode * 7) + UnitId.GetHashCode();
          return hashCode;
        }
        
        #endregion
    }

}
