//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPWorkflowAssignee {

        public CPWorkflowAssignee()
        {
            OnCreated();
        }

        public virtual long AssigneeId
        {
            get;
            set;
        }

        public virtual long InstanceId
        {
            get;
            set;
        }

        public virtual long UserId
        {
            get;
            set;
        }

        public virtual string CycleId
        {
            get;
            set;
        }

        public virtual int AssigneeStatus
        {
            get;
            set;
        }

        public virtual string StepId
        {
            get;
            set;
        }

        public virtual string StepNameCaption
        {
            get;
            set;
        }

        public virtual string StepCaption
        {
            get;
            set;
        }

        public virtual string Comments
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> DueDate
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> ProcessedDate
        {
            get;
            set;
        }

        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }

        public virtual CPUser CPUser
        {
            get;
            set;
        }

        public virtual CPWorkflowInstance CPWorkflowInstance
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
