//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPGroup {

        public CPGroup()
        {
            this.CPGroupRoles = new List<CPGroupRole>();
            this.CPGroups_ParentId = new List<CPGroup>();
            this.CPGroupUsers = new List<CPGroupUser>();
            OnCreated();
        }

        public virtual long GroupId
        {
            get;
            set;
        }

        public virtual System.Nullable<long> ParentId
        {
            get;
            set;
        }

        public virtual string GroupSId
        {
            get;
            set;
        }

        public virtual string GroupName
        {
            get;
            set;
        }

        public virtual string GroupCode
        {
            get;
            set;
        }

        public virtual IList<CPGroupRole> CPGroupRoles
        {
            get;
            set;
        }

        public virtual IList<CPGroup> CPGroups_ParentId
        {
            get;
            set;
        }

        public virtual CPGroup CPGroup_ParentId
        {
            get;
            set;
        }

        public virtual IList<CPGroupUser> CPGroupUsers
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
