//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPOnlineSession {

        public CPOnlineSession()
        {
            this.IsArabic = false;
            OnCreated();
        }

        public virtual long SessionId
        {
            get;
            set;
        }

        public virtual string SessionSId
        {
            get;
            set;
        }

        public virtual System.Nullable<long> UserId
        {
            get;
            set;
        }

        public virtual bool IsArabic
        {
            get;
            set;
        }

        public virtual System.DateTime LastActivityDateTime
        {
            get;
            set;
        }

        public virtual System.DateTime CreationDateTime
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
