//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-01-29 02:52:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace CitizenPortal.DAL
{
    public partial class CPLanguageDictionary {

        public CPLanguageDictionary()
        {
            OnCreated();
        }

        public virtual long LanguageDictionaryId
        {
            get;
            set;
        }

        public virtual System.Nullable<long> ParentId
        {
            get;
            set;
        }

        public virtual string LanguageDictionarySId
        {
            get;
            set;
        }

        public virtual string LanguageKey
        {
            get;
            set;
        }

        public virtual string English
        {
            get;
            set;
        }

        public virtual string Arabic
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
